name: weatherforecast
description: Flutter weather application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  geolocator: ^7.7.1
  dio: ^4.0.0
  logger: ^1.0.0
  shared_preferences: ^2.0.5
  pretty_dio_logger: ^1.2.0-beta-1
  fluro: ^2.0.3
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  lint: ^1.5.3
  mockito: ^5.0.9
  build_runner: ^2.0.4
  http_mock_adapter: ^0.2.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/